### ISSUE TITLE
Compilation fails with glibc 2.26

### ISSUE THREAD

**Issue by guzzard** [Kode/khacpp#1]
Created an issue in [hxcpp](https://github.com/HaxeFoundation/hxcpp/issues/641) but affects khacpp as well.

**Comment by guzzard** [comment]
@RobDangerous, this issue was fixed in hxcpp 21 of September, but it's still present in khacpp. Would it be possible to pull in that fix to khacpp as well?

**Comment by RobDangerous** [comment]
I pulled in everything. Where does it fail?

**Comment by guzzard** [comment]
@RobDangerous, sorry my khacpp was from 24th of Sept. When I updated to git master everything built fine! Closing!
