### ISSUE TITLE
sys.Thread.create doesn't work on android target

### ISSUE THREAD

**Issue by sannyun** [Kode/khacpp#12]
`sys.Thread.create` call freezes calling thread at https://github.com/Kode/khacpp/blob/ccb849301c390d15d925f6801b1acd7ea17e9bbe/src/hx/Thread.cpp#L309
It looks like `hxThreadFunc` that is passed as `HxCreateDetachedThread`'s param may not be called.
I noticed that khacpp's `HxCreateDetachedThread` definishion stores pointer to hxThreadFunc in local variable` kinc_thread_t thread`. And then pointer to it is passed to `pthread_create`. Could it be related?

This can be reproduced with minimal Kha project (`make --init`) and `Thread.create` placed somewhere in `main`, compiled for android (`make android-native...`)
```
        ...
	public static function main() {
		System.start({title: "Project", width: 1024, height: 768}, function (_) {
			// Just loading everything is ok for small projects
			Assets.loadEverything(function () {
				// Avoid passing update/render directly,
				// so replacing them via code injection works
				Scheduler.addTimeTask(function () { update(); }, 0, 1 / 60);
				System.notifyOnFrames(function (frames) { render(frames); });

				Thread .create(threadBody);
			});
		});
	}

	private static function threadBody(): Void {
		
		while (true) {
			Sys.sleep(1.0);
		}
	}
```

**Comment by tcdude** [comment]
This used to work for me, before I updated my local Kha repo. Is it possible that it broke when you removed the last Kore things and replaced with Kinc things?
